### ISSUE TITLE
Orders from Shopify not appearing

### ISSUE THREAD

**Issue by Brodali** [flagshipcompany/shopify-issues#4]
I have just reinstalled Flagship for Shopify and used a new credential for Flagship. My orders are not showing, how can I import them?

**Comment by jason-FLS** [comment]
Unfortunately, we don't have any means of importing orders directly to the app. 

The app will import any unshipped orders from the past 30 days upon installation, so if any orders don't meet this requirement, then you will not be able to work on them directly using the shopify app.

**Comment by Brodali** [comment]
I do have plenty of orders that fit the requirements, they are not importing.

**Comment by jason-FLS** [comment]
I think there might be a misunderstanding about what exactly you were expecting to happen upon installing the app, and I don't think it would be appropriate to try and troubleshoot with you in this method.

I think it would be better to have you contact us directly at developpers@flagshipcompany.com so that we can assist you for this.

**Comment by jason-FLS** [comment]
My mistake, I made a typo in the email address: please send it to developers@flagshipcompany.com.
